all: add agent.RunWithQueue
adevinta/vulcan-agent pull request #156
Opened 2023-07-27 12:16 UTC by jroimartin

This function takes a queue.ReadWriter as argument, which allows using
custom queue implementation. Therefore, it decouples the agent from
SQS.

2023-08-02 12:22 UTC, seilagamo requested changes

2023-08-02 12:22 UTC, seilagamo commented on agent/agent.go
> +	if (cfg.SQSReader != config.SQSReader{} || cfg.SQSWriter != config.SQSWriter{}) {
This condition makes the agent fails in SaaS mode

2023-08-02 12:22 UTC, seilagamo commented on agent/agent.go
> +		cancel()
In this case, would cancel also be executed before the return for being deferred?

2023-08-02 14:21 UTC, jroimartin commented on agent/agent.go
> +		cancel()
The [context package documentation](https://pkg.go.dev/context#CancelFunc) says:

> A CancelFunc may be called by multiple goroutines simultaneously. After the first call, subsequent calls to a CancelFunc do nothing. 

Actually, deferring the `cancel` call just after creating the context is considered a good practice to avoid context leaks.

>Failing to call the CancelFunc leaks the child and its children until the parent is canceled or the timer fires.

2023-08-02 14:22 UTC, jroimartin commented on agent/agent.go
> +	if (cfg.SQSReader != config.SQSReader{} || cfg.SQSWriter != config.SQSWriter{}) {
Good catch! I'll remove this check.

2023-08-04 09:27 UTC, seilagamo approved these changes
LGTM

2023-08-04 13:43 UTC, jesusfcr submitted a review, later dismissed

2023-08-07 08:56 UTC, jroimartin commented
@jesusfcr PTAL.

Diff: https://github.com/adevinta/vulcan-agent/compare/7291f61..c63138a

https://github.com/adevinta/vulcan-agent/pull/156/commits/ee0cd7d612106f5a046aacbf3d0c8636644d1e09: After refactoring the PR, `queue.ReadWriter` is not used anymore.

https://github.com/adevinta/vulcan-agent/pull/156/commits/c63138ad598ffac9ef72ed0490e2b1c18ce5c13a: After reading the documentation of `stateupdater.QueueWriter` again, I don't think it should be an alias of `queue.Writer`.

> QueueWriter defines the queue services used by an updater to send the status updates.

2023-08-08 14:10 UTC, jesusfcr approved these changes
LGTM

2023-08-09 05:05 UTC, merged