queue: add channels based queue implementation
adevinta/vulcan-agent pull request #157
Opened 2023-07-27 22:18 UTC by jroimartin

Add a local queue implementation based on channels.

2023-08-04 14:40 UTC, seilagamo requested changes
Minor changes in comments as usual

2023-08-07 08:35 UTC, jroimartin commented on queue/chanqueue/chanqueue.go
> +		c:             make(chan queue.Message),
I think `ChanQueue.Write` should never block. I assume the user of the API expects to write the message into the queue and let the consumers to process it asynchronously. Given this design choice, no matter the value we choose for the channel buffer capacity, we cannot guarantee that it will never block.

Besides that, we are already limiting the number of messages processed in parallel via the `queue.MessageProcessor.FreeTokens` channel. So, we don't have to worry about running out of resources because we are processing too many messages at the same time.

Thus, we need to decide how to persist the messages that are pending. I chose to use goroutines because they are very cheap in terms of memory and CPU overhead and it shouldn't be a problem to create [hundreds of thousands of them](https://go.dev/doc/faq#goroutines).

Now, in terms of performance, there are scenarios where choosing between a buffered and an unbuffered channel can have an impact. However, given the nature of the workloads we will handle (security checks that take a non negligible variable time to finish) I don't think it would make a big difference.

Maybe @manelmontilla can provide additional information.

2023-08-07 09:17 UTC, jesusfcr commented on queue/chanqueue/chanqueue.go
> +		c:             make(chan queue.Message),
Totally agree it should't block as it's not exposed as a channel.
I though just to change to buffered with a size of i.e. 1000, and keep the goroutines to prevent the blocking. This way the number of goroutines created would be the number of checks, but they will be automatically finished unless more than 1000 jobs. Totally agree there should be no difference in this use case, it's just to understand.
Thanks for the explanation.

2023-08-08 07:06 UTC, jesusfcr commented on queue/chanqueue/chanqueue.go
> +	case <-ctx.Done():
Thanks for the explanation.

2023-08-08 07:07 UTC, jesusfcr approved these changes
LGTM

2023-08-09 09:06 UTC, merged