Refactor to allow being reused as a client
adevinta/vulcan-agent pull request #45
Opened 2021-12-21 12:30 UTC by jesusfcr

2021-12-27 16:16 UTC, manelmontilla requested changes

2022-01-10 08:10 UTC, jesusfcr commented on backend/docker/docker.go
> +type RunConfig struct {
Done in d721507

2022-01-10 08:21 UTC, jesusfcr commented on backend/docker/docker.go
> +func BuildBackend(log log.Logger, cfg config.Config, hook Hook) (backend.Backend, error) {
Done in 754cfb1

2022-01-10 08:29 UTC, jesusfcr commented on backend/docker/docker.go
> +// Hook allows to update the docker configuration just before the container creation
done in 185d5f1

2022-01-10 10:28 UTC, jesusfcr commented on backend/docker/docker.go
> +	// TODO: Use a propper Arch
It was related to the Platform parameter, but it's optional so I removed the TODO in 83b4ab2

2022-01-10 12:34 UTC, jesusfcr commented on backend/docker/docker.go
> +			// TODO: Review how to manage this, ... generate an error?
result.Error is not an error. Instead I create an error with result.Error.Message in 1fb2a80 and fix the ctx.

2022-01-10 12:44 UTC, jesusfcr commented on backend/docker/docker.go
>  type Client interface {
Right, removed in 735987b

2022-01-10 13:10 UTC, jesusfcr commented on backend/docker/docker.go
> +	hook      Hook
What about updater / ConfigUpdater? See 40ad04b

2022-01-10 13:10 UTC, jesusfcr commented on backend/docker/docker.go
> +type Hook func(backend.RunParams, *RunConfig) error
What about ConfigUpdater? See 40ad04b

2022-01-10 15:08 UTC, jesusfcr commented on agent/agent.go
>  // passed BackendCreator. When the function finishes it returns an exit code of
Is this enough 8fa102b ?

2022-01-10 15:09 UTC, jesusfcr commented on backend/docker/docker.go
>  // CheckVars.
See 40ad04b

2022-01-11 08:57 UTC, manelmontilla commented on agent/agent.go
>  // passed BackendCreator. When the function finishes it returns an exit code of
It is, thanks!!

2022-01-11 08:57 UTC, manelmontilla commented on backend/docker/docker.go
> +type Hook func(backend.RunParams, *RunConfig) error
Yep I like it, much better than my suggestion.

2022-01-11 08:59 UTC, manelmontilla commented on backend/docker/docker.go
> +			// TODO: Review how to manage this, ... generate an error?
True!!, I like the solution 👍

2022-01-11 08:59 UTC, manelmontilla commented on backend/docker/docker.go
> +	// TODO: Use a propper Arch
ok thanks.

2022-01-11 09:00 UTC, manelmontilla commented on backend/docker/docker.go
> +	hook      Hook
Yep, good name.

2022-01-11 09:00 UTC, manelmontilla approved these changes
LGTM

2022-01-14 12:11 UTC, merged