improve pulls
adevinta/vulcan-agent pull request #46
Opened 2022-02-15 08:44 UTC by jesusfcr

- Improve pulls filtering by host
- Add pullPolicy
- Add tests
- Use docker stored creds for new registry domains
- Use github.com/docker/cli to get stored auth

2022-02-17 11:11 UTC, danfaizer requested changes
Great contribution @jesusfcr !
I've added some comments. Feel free to reach me in case something is not clear or I didn't catch it in the correct way.

2022-02-17 11:11 UTC, danfaizer commented on jobrunner/runner.go
> +		err = fmt.Errorf("unable to parse image %s - %+v", imageURI, err)
In this case, I would suggest to use `%w` instead of `%+v` in the fmt.Errorf in order to "wrap" errors.

2022-02-17 11:11 UTC, danfaizer commented on jobrunner/runner.go
> +	if domain == "docker.io" {
In order to avoid "harder-to-read" if else blocks, I would suggest:
```
checktypeName = fmt.Sprintf("%s/%s", domain, path)
if domain == "docker.io" {
	// Ignore docker.io and "library/" as we don't expect a check in docker.io/library.
	checktypeName = strings.TrimPrefix(path, "library/")
}
```

2022-02-17 11:11 UTC, danfaizer commented on resources/example.toml
> +server = "docker.artifactory.com"
I would suggest to user:
```
registry1.example.com
registry2.example.com
```
etc.

2022-02-17 16:35 UTC, jesusfcr commented on backend/docker/docker.go
> +		return nil, err
Right!

2022-02-17 16:40 UTC, jesusfcr commented on backend/docker/docker.go
> +func (b *Docker) addRegistryAuth(auth *types.AuthConfig) error {
Yep, much better this way!

2022-02-17 18:27 UTC, jesusfcr commented on backend/docker/docker.go
> +		b.log.Infof("an auth for %s already exists", auth.ServerAddress)
warn is not available (debug, info or error)

2022-02-17 18:28 UTC, jesusfcr commented on backend/docker/docker.go
> +func (b *Docker) getRegistryAuth(domain string) (*types.AuthConfig, error) {
Absolutely

2022-02-18 07:37 UTC, jesusfcr commented on backend/docker/docker.go
> +	if buf.String() != "" {
Right, I also completed some missing cases and moved that o a specific function.

2022-02-18 07:43 UTC, jesusfcr commented on backend/docker/docker.go
> +	return nil, nil
It was intended, It returned err when it was not able to GetAuthConfig. In any case, I refactored to not return error.

2022-02-18 07:44 UTC, jesusfcr commented on backend/docker/docker.go
> +		if len(images) == 1 {
Yes, I though about that, I made some tests and it was 1, but it could be safer to use >1 just in case.

2022-02-18 07:46 UTC, jesusfcr commented on backend/docker/docker.go
> +	// image was validated before and ParseImage always return a domain
Thanks. I like this conventions.

2022-02-18 08:20 UTC, jesusfcr commented on jobrunner/runner.go
> +		err = fmt.Errorf("unable to parse image %s - %+v", imageURI, err)
Right, thanks!

2022-02-18 08:27 UTC, jesusfcr commented on jobrunner/runner.go
> +	if domain == "docker.io" {
Ok

2022-02-18 08:31 UTC, jesusfcr commented on resources/example.toml
> +server = "docker.artifactory.com"
Ok

2022-02-25 08:33 UTC, danfaizer requested changes
A couple of minor details.

2022-02-25 08:33 UTC, danfaizer commented on backend/docker/docker.go
> +	b.log.Infof("Pulled image=%s domain=%s auth=%v time=%s err=%v", image, domain, pullOpts.RegistryAuth != "", int(time.Since(start).Seconds()), err)
A couple of minor details:

```
time="2022-02-25T08:23:39.994876756Z" level=info msg="Pulled image=REDACTED/vulcan-smtp-open-relay:544 
domain=REDACTED auth=true time=%!s(int=1) err=<nil>" hostname=REDACTED
```

`/Pulled/pulled`

and:
`time=%s`
to
`time=%d`

2022-02-25 08:42 UTC, danfaizer requested changes

2022-02-25 08:42 UTC, danfaizer commented on backend/docker/docker.go
> +	b.log.Debugf("Pulling image=%s domain=%s auth=%v", image, domain, pullOpts.RegistryAuth != "")
Minor detail:

`/Pulled/pulled`

2022-02-25 09:09 UTC, jesusfcr commented on backend/docker/docker.go
> +	b.log.Infof("Pulled image=%s domain=%s auth=%v time=%s err=%v", image, domain, pullOpts.RegistryAuth != "", int(time.Since(start).Seconds()), err)
last minute fixes :(
Thanks

2022-02-25 09:09 UTC, jesusfcr commented on backend/docker/docker.go
> +	b.log.Debugf("Pulling image=%s domain=%s auth=%v", image, domain, pullOpts.RegistryAuth != "")
Done

2022-02-25 10:27 UTC, manelmontilla commented on backend/docker/docker.go
> -	b.log.Debugf("fetching check required variables %+v", params.RequiredVars)
Just curious why do you prefer to not write, in the debug mode,  the Required wars that are going to be fetched?

2022-02-25 10:27 UTC, manelmontilla commented on backend/docker/docker.go
> +		b.log.Errorf("wrong credentials provided for %s %s error=%+v", domain, auth.ServerAddress, err)
We usually try to wrap lines at 80 columns, so I would wrap this line to something like:
``` 
b.log.Infof(
        "check: %s timeout or aborted ensure container %s is stopped",
        params.CheckID,
        contID,
)
```

2022-02-25 10:29 UTC, manelmontilla commented on backend/docker/docker.go
> +	b.log.Infof("pulled image=%s domain=%s auth=%v time=%d err=%v", image, domain, pullOpts.RegistryAuth != "", int(time.Since(start).Seconds()), err)
I would also wrap this line to something like:
```
	b.log.Infof(
        "Pulled image=%s domain=%s auth=%v time=%s err=%v",
        image,
        domain,
        pullOpts.RegistryAuth != "",
        int(time.Since(start).Seconds()),
        err,
    )
```

2022-02-25 11:57 UTC, jesusfcr commented on backend/docker/docker.go
> +	// Add the legacy single registry auth to the slice
Done

2022-02-25 11:57 UTC, jesusfcr commented on backend/docker/docker.go
> +		// This prevents the agent to start with wrong supplied credentials
done

2022-02-25 11:58 UTC, jesusfcr commented on backend/docker/docker.go
> +// addRegistryAuth adds the auth to the map only if valid
done

2022-02-25 11:59 UTC, jesusfcr commented on backend/docker/docker.go
> +		b.log.Errorf("wrong credentials provided for %s %s error=%+v", domain, auth.ServerAddress, err)
Ok, done

2022-02-25 12:06 UTC, jesusfcr commented on backend/docker/docker.go
> +	"github.com/adevinta/vulcan-agent/jobrunner"
Good point, I was not happy because of exactly what you said, I thought about putting it in docker as it is related to docker, but jobrunner doesn't knows about the docker package and I didn't want to add it because of the same reason.
Also I discarded backend as it was empty of functions, but I agree is the best place to put it.
Thanks!

2022-02-25 15:51 UTC, jesusfcr commented on backend/docker/docker.go
> +func validateEnum(value string, options []string, defaultValue string) (string, error) {
Great!

2022-02-25 15:51 UTC, jesusfcr commented on backend/docker/docker.go
> +const (
Love it! I didn't know about the Marshall magic.
Thanks!

2022-02-25 15:59 UTC, jesusfcr commented on backend/docker/docker.go
> +	// Build a pattern with the tag to prevent returning all the tags from the image
I don't see much point on printing this info. It depends on the check type definition that doesn't change over time, also no info about the check type, about the check id.

2022-02-25 16:02 UTC, jesusfcr commented on backend/docker/docker.go
> +	// Copy all the data (same struct indifferent packages)
done.

2022-02-25 16:03 UTC, jesusfcr commented on backend/docker/docker.go
> +	b.log.Infof("pulled image=%s domain=%s auth=%v time=%d err=%v", image, domain, pullOpts.RegistryAuth != "", int(time.Since(start).Seconds()), err)
done.

2022-02-25 16:11 UTC, jesusfcr commented on backend/docker/docker.go
> +func (b *Docker) getContainerlogs(ID string) ([]byte, error) {
Just to avoid copying the object just to call this function. 
I know this function doesn't modify the object and read about using a pointer only if the object is modified in the code.
WDYT?

2022-02-25 17:04 UTC, jesusfcr commented on backend/docker/docker.go
> +func (b *Docker) getRegistryAuth(domain string) *types.AuthConfig {
Done in  175c025

2022-02-25 17:05 UTC, jesusfcr commented on backend/docker/docker.go
> +func (b *Docker) addRegistryAuth(domain string, auth *types.AuthConfig) error {
This function uses logs and the docker client so I decided to keep it Docker and use the the functionality of the new object. Related to 175c025

2022-02-25 17:09 UTC, jesusfcr commented on backend/docker/docker.go
> -	b.log.Debugf("fetching check required variables %+v", params.RequiredVars)
I don't see much point on printing this info. It depends on the check type definition that doesn't change over time, also no info about the check type, about the check id. Even in debug mode.

2022-02-25 17:12 UTC, jesusfcr commented on backend/docker/docker.go
> +	auths     map[string]*types.AuthConfig
Done, not so sure if it this is what you had in mind 175c025

2022-02-28 08:59 UTC, jesusfcr commented on backend/docker/docker.go
> +const (
Also the adaptation of the client https://github.com/adevinta/vulcan-local/commit/105805b5263eb30a561102fe7a834d687617d6e8

2022-02-28 10:06 UTC, jesusfcr commented on backend/docker/docker.go
> +	auths     map[string]*types.AuthConfig
Also forgot to init the internal map https://github.com/adevinta/vulcan-agent/pull/46/commits/640bccf61db09e131c5ca97a0be8967ea6100237
Do you think it's the right approach?

2022-02-28 11:21 UTC, manelmontilla commented on backend/docker/docker.go
> -	b.log.Debugf("fetching check required variables %+v", params.RequiredVars)
Okey makes sense!!

2022-02-28 11:22 UTC, manelmontilla commented on backend/docker/docker.go
> +const (
👍

2022-02-28 11:23 UTC, manelmontilla commented on backend/docker/docker.go
> +func (b *Docker) addRegistryAuth(domain string, auth *types.AuthConfig) error {
Okey I agree makes sense

2022-02-28 11:24 UTC, manelmontilla commented on backend/docker/docker.go
> +func (b *Docker) getRegistryAuth(domain string) *types.AuthConfig {
Okey agree also with this, that is: keep the functionality here.

2022-02-28 11:27 UTC, manelmontilla commented on backend/docker/docker.go
> +func (b *Docker) getContainerlogs(ID string) ([]byte, error) {
Umm I understand, the thing is, if the calling site is holding a reference to this object, if this method is called, even when the receiver is not a reference, the object is not going to be copied, there would a dereference there but not a copy. In any case it's also not a big deal if you prefer to leave as it is, I mean with the receiver being a reference.

2022-02-28 11:36 UTC, manelmontilla commented on backend/docker/docker.go
> +	auths     map[string]*types.AuthConfig
Yes I do!!

2022-02-28 11:38 UTC, manelmontilla approved these changes
LGTM

2022-02-28 11:42 UTC, manelmontilla submitted a review, later dismissed
LGTM

2022-02-28 11:47 UTC, purple-team-service-user commented on backend/docker/docker.go
> +func (b *Docker) getContainerlogs(ID string) ([]byte, error) {
I didn't know that. Reverted

2022-02-28 11:50 UTC, manelmontilla approved these changes
LGTM

2022-02-28 14:38 UTC, danfaizer approved these changes
👍

2022-02-28 14:51 UTC, merged