Remove vulcan-results dependency
adevinta/vulcan-agent pull request #92
Opened 2023-05-17 16:27 UTC by danfaizer

This PR eliminates the dependency on vulcan-results.

Currently, vulcan-agent runs vulcan-checks, and then sends the resulting vulnerability report and raw logs to vulcan-results for storage. However, this process can be made more efficient by having vulcan-agent handle the file uploads directly, instead of relying on vulcan-results.

By removing this extra layer, we can avoid unnecessary roundtrips between services and improve scalability. This change means that the capacity for file uploads will automatically adjust to match the number of vulcan-agents, which is a more optimal solution in the long term.
Additionally, this modification has the potential to reduce costs by minimizing cpu and memory usage for vulcan-results and decreasing overall bandwidth consumption.

Merging this PR requires two previous changes:

1. Add S3 write permissions on the target buckets to the vulcan-agent IAM role.
2. Modify the vulcan-agent config to set up the new required parameters:
```
[s3_writer]
link_base = "http://vulcan-results.example.com/v1/"
bucket_reports = "my-vulcan-check-reports"
bucket_logs = "my-vulcan-check-logs"
region = "eu-west-1"
s3_link = false
```

These changes are necessary to enable the vulcan-agent to directly upload the reports and logs to the specified S3 buckets without relying on vulcan-results.

2023-05-18 11:25 UTC, jesusfcr commented on agent/agent.go
>  func Run(cfg config.Config, b backend.Backend, l log.Logger) int {
I would move the Uploader config outside the Run

- Define Uploader as a simple interface with the send methods.
- adding a new parameter uploader that implements that `Uploader` interface
- Create the S3Uploader that implements this Uploader interface and is configured in the main.go.

With this simple trick will allow i.e. `lava` to provide a trivial implementation to receive the data.

2023-05-19 14:18 UTC, julianvilas requested changes
Very good job mate! Just some minor comments.

2023-05-19 14:18 UTC, julianvilas commented on storage/s3/writer.go
> +	key = fmt.Sprintf("%s/%s.%s", kind, checkID, extension)
Just out of curiosity: we are not using anymore the date partitioning schema for the athena queries, right?

2023-05-19 14:18 UTC, julianvilas commented on storage/s3/writer_test.go
> +			contentType:   "test/json",
Shouldn't this be `text` instead?

2023-05-19 14:18 UTC, julianvilas commented on storage/s3/writer_test.go
> +			contentType:   "test/plain",
Shouldn't this be `text` instead?

2023-05-19 14:18 UTC, julianvilas commented on storage/s3/writer_test.go
> +			contentType:   "test/json",
Shouldn't this be `text` instead?

2023-05-19 14:18 UTC, julianvilas commented on storage/s3/writer_test.go
> +			contentType:   "test/plain",
Shouldn't this be `text` instead?

2023-05-19 14:46 UTC, danfaizer commented on storage/s3/writer.go
> +// Writer writes messages to and AWS SQS queue.
Changed the text in [bfe293b](https://github.com/adevinta/vulcan-agent/pull/92/commits/bfe293b89d2a4998909920e0f9939708af6ecab3).
Thanks!

2023-05-19 14:47 UTC, danfaizer commented on storage/s3/writer.go
> +	dt := startedAt.Format("dt=2006-01-02")
Absolutely right. Moved inside the `if` in [bfe293b](https://github.com/adevinta/vulcan-agent/pull/92/commits/bfe293b89d2a4998909920e0f9939708af6ecab3).
In fact, probably in future refactors that block may be deleted.

2023-05-19 14:51 UTC, danfaizer commented on storage/s3/writer_test.go
> +			contentType:   "test/json",
Thanks for reporting the typo. Resolved in [bfe293b](https://github.com/adevinta/vulcan-agent/pull/92/commits/bfe293b89d2a4998909920e0f9939708af6ecab3).

2023-05-19 14:51 UTC, danfaizer commented on storage/s3/writer_test.go
> +			contentType:   "test/plain",
Same as above.

2023-05-19 14:51 UTC, danfaizer commented on storage/s3/writer_test.go
> +			contentType:   "test/json",
Same as above.

2023-05-19 14:51 UTC, danfaizer commented on storage/s3/writer_test.go
> +			contentType:   "test/plain",
Same as above.

2023-05-22 09:31 UTC, julianvilas commented on storage/s3/writer.go
> +	key = fmt.Sprintf("%s/%s.%s", kind, checkID, extension)
Gotcha, thx! :)

2023-05-22 09:32 UTC, julianvilas approved these changes

2023-05-22 13:17 UTC, merged